export const DAFTAR_RHK = [
  "Melaksanakan proses pembelajaran di dalam kelas",
  "Melaksanakan kegiatan praktik di laboratorium/bengkel",
  "Menjadi Wali Kelas",
  "Menjadi Guru Piket Harian",
  "Menjadi Pembina Ekstrakurikuler Pramuka",
  "Menjadi Pembina Ekstrakurikuler Olahraga",
  "Menjadi Pembina Ekstrakurikuler Seni",
  "Menjadi Pembina Ekstrakurikuler Keagamaan",
  "Mengikuti kegiatan KKG/MGMP",
  "Mengikuti Seminar Pendidikan (Webinar/Luring)",
  "Mengikuti Workshop Pengembangan Kompetensi Guru",
  "Menjadi Pengawas Ujian Sekolah",
  "Menjadi Pengawas Asesmen Nasional (ANBK)",
  "Menjadi Panitia Kegiatan Sekolah (PHBI/PHBN)",
  "Menyusun Perangkat Pembelajaran (RPP/Modul Ajar)",
  "Membuat Media Pembelajaran Inovatif",
  "Menyusun Alat Peraga Edukatif",
  "Melaksanakan Remedial dan Pengayaan",
  "Melakukan Penilaian Hasil Belajar Siswa",
  "Menjadi Tim Penilai Kinerja Guru (PKG)",
  "Menjadi Tutor/Instruktur Sebaya",
  "Melakukan Kunjungan Rumah (Home Visit)",
  "Membimbing Guru Pemula (Induksi)",
  "Mengikuti Pelatihan Mandiri di Platform Merdeka Mengajar",
  "Menjadi Kontributor Konten Pendidikan",
  "Menulis Karya Ilmiah Populer di Media Massa",
  "Menulis Artikel Ilmiah di Jurnal Pendidikan",
  "Membuat Penelitian Tindakan Kelas (PTK)",
  "Menjadi Narasumber Kegiatan Pendidikan",
  "Menjadi Juri Lomba Tingkat Sekolah",
  "Menjadi Juri Lomba Tingkat Kecamatan/Kabupaten",
  "Membimbing Siswa Mengikuti Lomba Akademik",
  "Membimbing Siswa Mengikuti Lomba Non-Akademik",
  "Aktif dalam Organisasi Profesi (PGRI/IGI)",
  "Melaksanakan Tugas Tambahan Wakil Kepala Sekolah",
  "Melaksanakan Tugas Tambahan Kepala Perpustakaan",
  "Melaksanakan Tugas Tambahan Kepala Laboratorium",
  "Mengelola Program UKS",
  "Melaksanakan Kegiatan Literasi Sekolah",
  "Melaksanakan Kegiatan P5 (Projek Penguatan Profil Pelajar Pancasila)",
  "Mengikuti Upacara Bendera Hari Senin",
  "Mengikuti Upacara Peringatan Hari Besar Nasional",
  "Melaksanakan Rapat Dinas Sekolah",
  "Melaksanakan Rapat Evaluasi Belajar",
  "Menyusun Soal Ujian/Asesmen",
  "Mengoreksi Lembar Jawaban Ujian",
  "Mengisi Raport Hasil Belajar Siswa",
  "Melakukan Konseling Terhadap Siswa Bermasalah",
  "Mengikuti Kegiatan Sosial Kemasyarakatan Sekolah",
  "Menjaga Kebersihan dan Keindahan Lingkungan Sekolah"
];